job_id: tree-pruner-dcef2944-56b5-4250-9db5-5b40567fcfed
email: sstoudt@smith.edu
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Alectoris_chukar, Perdix_perdix, Phasianus_colchicus, Pavo_cristatus, Dendragapus_canadensis,
  Dendragapus_obscurus, Bonasa_umbellus, Tympanuchus_phasianellus, Tympanuchus_cupido,
  Meleagris_gallopavo, Callipepla_squamata, Callipepla_californica, Callipepla_gambelii,
  Colinus_virginianus, Cyrtonyx_montezumae, Dendrocygna_bicolor, Dendrocygna_autumnalis,
  Oxyura_jamaicensis, Cygnus_olor, Cygnus_buccinator, Cygnus_columbianus, Anser_albifrons,
  Chen_caerulescens, Chen_rossii, Branta_canadensis, Branta_bernicla, Alopochen_aegyptiaca,
  Aix_sponsa, Anas_strepera, Anas_americana, Anas_rubripes, Anas_platyrhynchos, Anas_discors,
  Anas_cyanoptera, Anas_clypeata, Anas_acuta, Anas_crecca, Aythya_valisineria, Aythya_americana,
  Aythya_collaris, Aythya_marila, Aythya_affinis, Somateria_mollissima, Histrionicus_histrionicus,
  Clangula_hyemalis, Melanitta_perspicillata, Bucephala_clangula, Bucephala_islandica,
  Bucephala_albeola, Lophodytes_cucullatus, Mergus_serrator, Mergus_merganser, Melanerpes_lewis,
  Melanerpes_erythrocephalus, Melanerpes_formicivorus, Melanerpes_uropygialis, Melanerpes_carolinus,
  Melanerpes_aurifrons, Sphyrapicus_varius, Sphyrapicus_ruber, Picoides_nuttallii,
  Picoides_scalaris, Picoides_pubescens, Picoides_villosus, Picoides_arcticus, Colaptes_auratus,
  Colaptes_chrysoides, Dryocopus_pileatus, Megaceryle_alcyon, Megaceryle_torquata,
  Chloroceryle_americana, Coccyzus_erythropthalmus, Coccyzus_americanus, Crotophaga_sulcirostris,
  Geococcyx_californianus, Myiopsitta_monachus, Chaetura_pelagica, Aeronautes_saxatalis,
  Cynanthus_latirostris, Amazilia_yucatanensis, Archilochus_colubris, Archilochus_alexandri,
  Calypte_anna, Calypte_costae, Stellula_calliope, Selasphorus_platycercus, Selasphorus_rufus,
  Selasphorus_sasin, Tyto_alba, Megascops_kennicottii, Megascops_asio, Bubo_virginianus,
  Strix_varia, Glaucidium_gnoma, Athene_cunicularia, Aegolius_acadicus, Asio_otus,
  Asio_flammeus, Chordeiles_acutipennis, Chordeiles_minor, Phalaenoptilus_nuttallii,
  Caprimulgus_carolinensis, Columba_livia, Patagioenas_fasciata, Streptopelia_decaocto,
  Zenaida_macroura, Zenaida_asiatica, Columbina_inca, Columbina_passerina, Grus_canadensis,
  Grus_americana, Aramus_guarauna, Rallus_limicola, Porzana_carolina, Porphyrio_martinica,
  Fulica_americana, Scolopax_minor, Limosa_fedoa, Numenius_phaeopus, Numenius_americanus,
  Bartramia_longicauda, Tringa_melanoleuca, Tringa_flavipes, Tringa_solitaria, Actitis_macularius,
  Heteroscelus_incanus, Catoptrophorus_semipalmatus, Arenaria_interpres, Limnodromus_griseus,
  Limnodromus_scolopaceus, Calidris_alba, Calidris_pusilla, Calidris_mauri, Calidris_minutilla,
  Calidris_bairdii, Calidris_melanotos, Calidris_maritima, Calidris_alpina, Steganopus_tricolor,
  Phalaropus_lobatus, Haematopus_palliatus, Recurvirostra_americana, Pluvialis_fulva,
  Pluvialis_squatarola, Charadrius_semipalmatus, Charadrius_wilsonia, Charadrius_vociferus,
  Charadrius_melodus, Stercorarius_longicaudus, Rynchops_niger, Larus_delawarensis,
  Larus_californicus, Larus_philadelphia, Larus_pipixcan, Larus_minutus, Sterna_hirundo,
  Sterna_forsteri, Chlidonias_niger, Pandion_haliaetus, Elanoides_forficatus, Elanus_leucurus,
  Ictinia_mississippiensis, Haliaeetus_leucocephalus, Accipiter_striatus, Accipiter_cooperii,
  Accipiter_gentilis, Buteogallus_anthracinus, Parabuteo_unicinctus, Buteo_lineatus,
  Buteo_platypterus, Buteo_brachyurus, Buteo_swainsoni, Buteo_albicaudatus, Buteo_albonotatus,
  Buteo_jamaicensis, Buteo_regalis, Buteo_lagopus, Aquila_chrysaetos, Falco_sparverius,
  Falco_columbarius, Falco_mexicanus, Falco_peregrinus, Tachybaptus_dominicus, Podilymbus_podiceps,
  Podiceps_grisegena, Podiceps_auritus, Podiceps_nigricollis, Aechmophorus_occidentalis,
  Aechmophorus_clarkii, Anhinga_anhinga, Phalacrocorax_brasilianus, Phalacrocorax_carbo,
  Ixobrychus_exilis, Botaurus_lentiginosus, Nyctanassa_violacea, Nycticorax_nycticorax,
  Egretta_rufescens, Egretta_tricolor, Egretta_caerulea, Egretta_thula, Ardea_herodias,
  Casmerodius_albus, Bubulcus_ibis, Eudocimus_albus, Plegadis_falcinellus, Plegadis_chihi,
  Platalea_ajaja, Pelecanus_erythrorhynchos, Pelecanus_occidentalis, Coragyps_atratus,
  Cathartes_aura, Mycteria_americana, Gavia_stellata, Gavia_immer, Contopus_cooperi,
  Contopus_sordidulus, Contopus_virens, Empidonax_virescens, Empidonax_traillii, Empidonax_minimus,
  Empidonax_difficilis, Sayornis_phoebe, Sayornis_saya, Sayornis_nigricans, Pyrocephalus_rubinus,
  Myiarchus_crinitus, Myiarchus_tyrannulus, Tyrannus_melancholicus, Tyrannus_couchii,
  Tyrannus_forficatus, Tyrannus_tyrannus, Tyrannus_dominicensis, Pitangus_sulphuratus,
  Lanius_ludovicianus, Vireo_bellii, Vireo_atricapilla, Vireo_huttoni, Vireo_griseus,
  Vireo_solitarius, Vireo_flavifrons, Vireo_olivaceus, Vireo_gilvus, Cyanocitta_cristata,
  Cyanocitta_stelleri, Aphelocoma_californica, Perisoreus_canadensis, Nucifraga_columbiana,
  Corvus_brachyrhynchos, Corvus_ossifragus, Corvus_corax, Phainopepla_nitens, Bombycilla_garrulus,
  Bombycilla_cedrorum, Cinclus_mexicanus, Zoothera_naevia, Sialia_sialis, Sialia_mexicana,
  Sialia_currucoides, Myadestes_townsendi, Catharus_fuscescens, Catharus_minimus,
  Catharus_guttatus, Hylocichla_mustelina, Turdus_migratorius, Sturnus_vulgaris, Dumetella_carolinensis,
  Mimus_polyglottos, Toxostoma_rufum, Toxostoma_curvirostre, Toxostoma_redivivum,
  Sitta_pygmaea, Sitta_pusilla, Sitta_canadensis, Sitta_carolinensis, Certhia_americana,
  Campylorhynchus_brunneicapillus, Salpinctes_obsoletus, Catherpes_mexicanus, Cistothorus_platensis,
  Cistothorus_palustris, Thryomanes_bewickii, Thryothorus_ludovicianus, Troglodytes_aedon,
  Auriparus_flaviceps, Polioptila_caerulea, Parus_carolinensis, Parus_atricapillus,
  Parus_gambeli, Parus_rufescens, Baeolophus_inornatus, Baeolophus_bicolor, Baeolophus_atricristatus,
  Psaltriparus_minimus, Tachycineta_bicolor, Tachycineta_thalassina, Progne_subis,
  Stelgidopteryx_serripennis, Hirundo_rustica, Petrochelidon_pyrrhonota, Petrochelidon_fulva,
  Regulus_calendula, Regulus_satrapa, Chamaea_fasciata, Eremophila_alpestris, Passer_domesticus,
  Passer_montanus, Anthus_rubescens, Carduelis_pinus, Carduelis_tristis, Carduelis_psaltria,
  Carduelis_lawrencei, Carduelis_flammea, Leucosticte_tephrocotis, Carpodacus_purpureus,
  Carpodacus_cassinii, Carpodacus_mexicanus, Pinicola_enucleator, Loxia_leucoptera,
  Coccothraustes_vespertinus, Calcarius_lapponicus, Plectrophenax_nivalis, Calamospiza_melanocorys,
  Passerella_iliaca, Melospiza_melodia, Melospiza_lincolnii, Melospiza_georgiana,
  Zonotrichia_querula, Zonotrichia_albicollis, Zonotrichia_leucophrys, Zonotrichia_atricapilla,
  Junco_hyemalis, Passerculus_sandwichensis, Ammodramus_maritimus, Ammodramus_savannarum,
  Spizella_arborea, Spizella_passerina, Spizella_pallida, Spizella_breweri, Spizella_pusilla,
  Pooecetes_gramineus, Chondestes_grammacus, Amphispiza_bilineata, Amphispiza_belli,
  Aimophila_cassinii, Aimophila_ruficeps, Pipilo_chlorurus, Pipilo_maculatus, Pipilo_erythrophthalmus,
  Pipilo_crissalis, Vermivora_pinus, Vermivora_chrysoptera, Vermivora_peregrina, Vermivora_celata,
  Parula_americana, Dendroica_petechia, Dendroica_magnolia, Dendroica_tigrina, Dendroica_coronata,
  Dendroica_nigrescens, Dendroica_townsendi, Dendroica_occidentalis, Dendroica_virens,
  Dendroica_fusca, Dendroica_dominica, Dendroica_pinus, Dendroica_discolor, Dendroica_palmarum,
  Dendroica_castanea, Dendroica_striata, Dendroica_cerulea, Mniotilta_varia, Setophaga_ruticilla,
  Protonotaria_citrea, Helmitheros_vermivorum, Seiurus_aurocapilla, Seiurus_noveboracensis,
  Seiurus_motacilla, Oporornis_philadelphia, Oporornis_tolmiei, Geothlypis_trichas,
  Wilsonia_citrina, Wilsonia_pusilla, Wilsonia_canadensis, Myioborus_pictus, Icteria_virens,
  Piranga_rubra, Piranga_olivacea, Piranga_ludoviciana, Spiza_americana, Pheucticus_ludovicianus,
  Pheucticus_melanocephalus, Cardinalis_cardinalis, Cardinalis_sinuatus, Passerina_caerulea,
  Passerina_amoena, Passerina_cyanea, Passerina_versicolor, Passerina_ciris, Icterus_galbula,
  Icterus_bullockii, Icterus_cucullatus, Icterus_spurius, Icterus_parisorum, Xanthocephalus_xanthocephalus,
  Agelaius_phoeniceus, Agelaius_tricolor, Sturnella_magna, Sturnella_neglecta, Quiscalus_mexicanus,
  Quiscalus_major, Quiscalus_quiscula, Euphagus_carolinus, Euphagus_cyanocephalus,
  Molothrus_aeneus, Molothrus_ater, Dolichonyx_oryzivorus, Pica_hudsonia, Dendragapus_fuliginosus,
  Branta_hutchinsii, Anas_fulvigula, Himantopus_mexicanus, Caracara_cheriway, Butorides_virescens,
  Gavia_pacifica]
sample_trees: [EricsonStage2Full_5125.tre, EricsonStage2Full_2401.tre, EricsonStage2Full_1418.tre,
  EricsonStage2Full_9461.tre, EricsonStage2Full_6870.tre, EricsonStage2Full_6157.tre,
  EricsonStage2Full_9711.tre, EricsonStage2Full_2740.tre, EricsonStage2Full_7682.tre,
  EricsonStage2Full_5916.tre, EricsonStage2Full_9242.tre, EricsonStage2Full_2071.tre,
  EricsonStage2Full_5240.tre, EricsonStage2Full_8924.tre, EricsonStage2Full_8462.tre,
  EricsonStage2Full_0747.tre, EricsonStage2Full_1552.tre, EricsonStage2Full_7820.tre,
  EricsonStage2Full_1102.tre, EricsonStage2Full_5001.tre, EricsonStage2Full_4035.tre,
  EricsonStage2Full_1161.tre, EricsonStage2Full_5090.tre, EricsonStage2Full_1039.tre,
  EricsonStage2Full_2470.tre, EricsonStage2Full_1478.tre, EricsonStage2Full_7307.tre,
  EricsonStage2Full_4898.tre, EricsonStage2Full_5751.tre, EricsonStage2Full_9765.tre,
  EricsonStage2Full_2109.tre, EricsonStage2Full_7451.tre, EricsonStage2Full_6780.tre,
  EricsonStage2Full_6079.tre, EricsonStage2Full_2450.tre, EricsonStage2Full_2034.tre,
  EricsonStage2Full_3830.tre, EricsonStage2Full_1997.tre, EricsonStage2Full_0859.tre,
  EricsonStage2Full_0890.tre, EricsonStage2Full_9128.tre, EricsonStage2Full_9706.tre,
  EricsonStage2Full_2398.tre, EricsonStage2Full_9611.tre, EricsonStage2Full_4081.tre,
  EricsonStage2Full_9767.tre, EricsonStage2Full_2562.tre, EricsonStage2Full_9713.tre,
  EricsonStage2Full_8711.tre, EricsonStage2Full_1773.tre, EricsonStage2Full_5265.tre,
  EricsonStage2Full_2715.tre, EricsonStage2Full_2141.tre, EricsonStage2Full_6998.tre,
  EricsonStage2Full_4444.tre, EricsonStage2Full_8084.tre, EricsonStage2Full_6193.tre,
  EricsonStage2Full_3049.tre, EricsonStage2Full_1499.tre, EricsonStage2Full_2737.tre,
  EricsonStage2Full_0801.tre, EricsonStage2Full_2655.tre, EricsonStage2Full_9671.tre,
  EricsonStage2Full_1829.tre, EricsonStage2Full_4526.tre, EricsonStage2Full_9322.tre,
  EricsonStage2Full_3290.tre, EricsonStage2Full_2016.tre, EricsonStage2Full_2468.tre,
  EricsonStage2Full_3420.tre, EricsonStage2Full_3393.tre, EricsonStage2Full_1012.tre,
  EricsonStage2Full_2479.tre, EricsonStage2Full_0561.tre, EricsonStage2Full_8782.tre,
  EricsonStage2Full_5524.tre, EricsonStage2Full_5538.tre, EricsonStage2Full_5576.tre,
  EricsonStage2Full_9658.tre, EricsonStage2Full_0101.tre, EricsonStage2Full_2731.tre,
  EricsonStage2Full_3611.tre, EricsonStage2Full_8107.tre, EricsonStage2Full_4034.tre,
  EricsonStage2Full_4477.tre, EricsonStage2Full_9735.tre, EricsonStage2Full_1724.tre,
  EricsonStage2Full_2467.tre, EricsonStage2Full_3435.tre, EricsonStage2Full_4586.tre,
  EricsonStage2Full_1398.tre, EricsonStage2Full_1412.tre, EricsonStage2Full_3829.tre,
  EricsonStage2Full_4015.tre, EricsonStage2Full_7315.tre, EricsonStage2Full_3888.tre,
  EricsonStage2Full_8087.tre, EricsonStage2Full_8568.tre, EricsonStage2Full_4283.tre,
  EricsonStage2Full_2408.tre]
status: COMPLETED
created_at: "2021-06-01T16:25:15Z"
completed_at: "2021-06-01T16:26:06Z"
bad_names: {EricsonStage2Full_0101.tre: [], EricsonStage2Full_0561.tre: [], EricsonStage2Full_0747.tre: [],
  EricsonStage2Full_0801.tre: [], EricsonStage2Full_0859.tre: [], EricsonStage2Full_0890.tre: [],
  EricsonStage2Full_1012.tre: [], EricsonStage2Full_1039.tre: [], EricsonStage2Full_1102.tre: [],
  EricsonStage2Full_1161.tre: [], EricsonStage2Full_1398.tre: [], EricsonStage2Full_1412.tre: [],
  EricsonStage2Full_1418.tre: [], EricsonStage2Full_1478.tre: [], EricsonStage2Full_1499.tre: [],
  EricsonStage2Full_1552.tre: [], EricsonStage2Full_1724.tre: [], EricsonStage2Full_1773.tre: [],
  EricsonStage2Full_1829.tre: [], EricsonStage2Full_1997.tre: [], EricsonStage2Full_2016.tre: [],
  EricsonStage2Full_2034.tre: [], EricsonStage2Full_2071.tre: [], EricsonStage2Full_2109.tre: [],
  EricsonStage2Full_2141.tre: [], EricsonStage2Full_2398.tre: [], EricsonStage2Full_2401.tre: [],
  EricsonStage2Full_2408.tre: [], EricsonStage2Full_2450.tre: [], EricsonStage2Full_2467.tre: [],
  EricsonStage2Full_2468.tre: [], EricsonStage2Full_2470.tre: [], EricsonStage2Full_2479.tre: [],
  EricsonStage2Full_2562.tre: [], EricsonStage2Full_2655.tre: [], EricsonStage2Full_2715.tre: [],
  EricsonStage2Full_2731.tre: [], EricsonStage2Full_2737.tre: [], EricsonStage2Full_2740.tre: [],
  EricsonStage2Full_3049.tre: [], EricsonStage2Full_3290.tre: [], EricsonStage2Full_3393.tre: [],
  EricsonStage2Full_3420.tre: [], EricsonStage2Full_3435.tre: [], EricsonStage2Full_3611.tre: [],
  EricsonStage2Full_3829.tre: [], EricsonStage2Full_3830.tre: [], EricsonStage2Full_3888.tre: [],
  EricsonStage2Full_4015.tre: [], EricsonStage2Full_4034.tre: [], EricsonStage2Full_4035.tre: [],
  EricsonStage2Full_4081.tre: [], EricsonStage2Full_4283.tre: [], EricsonStage2Full_4444.tre: [],
  EricsonStage2Full_4477.tre: [], EricsonStage2Full_4526.tre: [], EricsonStage2Full_4586.tre: [],
  EricsonStage2Full_4898.tre: [], EricsonStage2Full_5001.tre: [], EricsonStage2Full_5090.tre: [],
  EricsonStage2Full_5125.tre: [], EricsonStage2Full_5240.tre: [], EricsonStage2Full_5265.tre: [],
  EricsonStage2Full_5524.tre: [], EricsonStage2Full_5538.tre: [], EricsonStage2Full_5576.tre: [],
  EricsonStage2Full_5751.tre: [], EricsonStage2Full_5916.tre: [], EricsonStage2Full_6079.tre: [],
  EricsonStage2Full_6157.tre: [], EricsonStage2Full_6193.tre: [], EricsonStage2Full_6780.tre: [],
  EricsonStage2Full_6870.tre: [], EricsonStage2Full_6998.tre: [], EricsonStage2Full_7307.tre: [],
  EricsonStage2Full_7315.tre: [], EricsonStage2Full_7451.tre: [], EricsonStage2Full_7682.tre: [],
  EricsonStage2Full_7820.tre: [], EricsonStage2Full_8084.tre: [], EricsonStage2Full_8087.tre: [],
  EricsonStage2Full_8107.tre: [], EricsonStage2Full_8462.tre: [], EricsonStage2Full_8568.tre: [],
  EricsonStage2Full_8711.tre: [], EricsonStage2Full_8782.tre: [], EricsonStage2Full_8924.tre: [],
  EricsonStage2Full_9128.tre: [], EricsonStage2Full_9242.tre: [], EricsonStage2Full_9322.tre: [],
  EricsonStage2Full_9461.tre: [], EricsonStage2Full_9611.tre: [], EricsonStage2Full_9658.tre: [],
  EricsonStage2Full_9671.tre: [], EricsonStage2Full_9706.tre: [], EricsonStage2Full_9711.tre: [],
  EricsonStage2Full_9713.tre: [], EricsonStage2Full_9735.tre: [], EricsonStage2Full_9765.tre: [],
  EricsonStage2Full_9767.tre: []}
