job_id: tree-pruner-ed3d7a63-57e3-4fc3-9780-21e8bfe6d1dc
email: sas072@bucknell.edu
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Alectoris_chukar, Perdix_perdix, Phasianus_colchicus, Pavo_cristatus, Dendragapus_canadensis,
  Dendragapus_obscurus, Bonasa_umbellus, Centrocercus_urophasianus, Tympanuchus_phasianellus,
  Tympanuchus_cupido, Meleagris_gallopavo, Oreortyx_pictus, Callipepla_squamata, Callipepla_californica,
  Callipepla_gambelii, Colinus_virginianus, Cyrtonyx_montezumae, Dendrocygna_bicolor,
  Dendrocygna_autumnalis, Oxyura_jamaicensis, Cygnus_olor, Cygnus_buccinator, Cygnus_columbianus,
  Anser_albifrons, Chen_caerulescens, Chen_rossii, Branta_canadensis, Branta_bernicla,
  Alopochen_aegyptiaca, Aix_sponsa, Anas_strepera, Anas_americana, Anas_rubripes,
  Anas_platyrhynchos, Anas_discors, Anas_cyanoptera, Anas_clypeata, Anas_acuta, Anas_crecca,
  Aythya_valisineria, Aythya_americana, Aythya_collaris, Aythya_marila, Aythya_affinis,
  Somateria_mollissima, Somateria_spectabilis, Histrionicus_histrionicus, Clangula_hyemalis,
  Melanitta_perspicillata, Bucephala_clangula, Bucephala_islandica, Bucephala_albeola,
  Lophodytes_cucullatus, Mergus_serrator, Mergus_merganser, Melanerpes_lewis, Melanerpes_erythrocephalus,
  Melanerpes_formicivorus, Melanerpes_uropygialis, Melanerpes_carolinus, Melanerpes_aurifrons,
  Sphyrapicus_varius, Sphyrapicus_ruber, Sphyrapicus_thyroideus, Picoides_nuttallii,
  Picoides_scalaris, Picoides_pubescens, Picoides_borealis, Picoides_villosus, Picoides_albolarvatus,
  Picoides_arcticus, Colaptes_auratus, Colaptes_chrysoides, Dryocopus_pileatus, Megaceryle_alcyon,
  Megaceryle_torquata, Chloroceryle_americana, Coccyzus_erythropthalmus, Coccyzus_americanus,
  Crotophaga_sulcirostris, Geococcyx_californianus, Myiopsitta_monachus, Cypseloides_niger,
  Chaetura_pelagica, Chaetura_vauxi, Aeronautes_saxatalis, Cynanthus_latirostris,
  Amazilia_yucatanensis, Archilochus_colubris, Archilochus_alexandri, Calypte_anna,
  Calypte_costae, Stellula_calliope, Selasphorus_platycercus, Selasphorus_rufus, Selasphorus_sasin,
  Tyto_alba, Otus_flammeolus, Megascops_kennicottii, Megascops_asio, Bubo_virginianus,
  Strix_varia, Glaucidium_gnoma, Micrathene_whitneyi, Athene_cunicularia, Aegolius_funereus,
  Aegolius_acadicus, Asio_otus, Asio_flammeus, Chordeiles_acutipennis, Chordeiles_minor,
  Phalaenoptilus_nuttallii, Caprimulgus_carolinensis, Caprimulgus_vociferus, Columba_livia,
  Patagioenas_fasciata, Streptopelia_decaocto, Zenaida_macroura, Zenaida_asiatica,
  Columbina_inca, Columbina_passerina, Grus_canadensis, Grus_americana, Aramus_guarauna,
  Coturnicops_noveboracensis, Rallus_elegans, Rallus_limicola, Porzana_carolina, Porphyrio_martinica,
  Fulica_americana, Scolopax_minor, Limosa_haemastica, Limosa_fedoa, Numenius_phaeopus,
  Numenius_americanus, Bartramia_longicauda, Tringa_melanoleuca, Tringa_flavipes,
  Tringa_solitaria, Actitis_macularius, Heteroscelus_incanus, Catoptrophorus_semipalmatus,
  Arenaria_interpres, Limnodromus_griseus, Limnodromus_scolopaceus, Calidris_canutus,
  Calidris_alba, Calidris_pusilla, Calidris_mauri, Calidris_minutilla, Calidris_bairdii,
  Calidris_melanotos, Calidris_maritima, Calidris_alpina, Calidris_himantopus, Steganopus_tricolor,
  Phalaropus_lobatus, Phalaropus_fulicarius, Haematopus_palliatus, Recurvirostra_americana,
  Pluvialis_fulva, Pluvialis_squatarola, Charadrius_semipalmatus, Charadrius_wilsonia,
  Charadrius_vociferus, Charadrius_melodus, Charadrius_montanus, Stercorarius_longicaudus,
  Stercorarius_parasiticus, Rynchops_niger, Larus_delawarensis, Larus_californicus,
  Larus_philadelphia, Larus_pipixcan, Larus_minutus, Sterna_hirundo, Sterna_paradisaea,
  Sterna_forsteri, Chlidonias_niger, Pandion_haliaetus, Elanoides_forficatus, Elanus_leucurus,
  Ictinia_mississippiensis, Haliaeetus_leucocephalus, Accipiter_striatus, Accipiter_cooperii,
  Accipiter_gentilis, Buteogallus_anthracinus, Parabuteo_unicinctus, Buteo_lineatus,
  Buteo_platypterus, Buteo_brachyurus, Buteo_swainsoni, Buteo_albicaudatus, Buteo_albonotatus,
  Buteo_jamaicensis, Buteo_regalis, Buteo_lagopus, Aquila_chrysaetos, Falco_sparverius,
  Falco_columbarius, Falco_mexicanus, Falco_peregrinus, Tachybaptus_dominicus, Podilymbus_podiceps,
  Podiceps_grisegena, Podiceps_auritus, Podiceps_nigricollis, Aechmophorus_occidentalis,
  Aechmophorus_clarkii, Anhinga_anhinga, Phalacrocorax_brasilianus, Phalacrocorax_carbo,
  Ixobrychus_exilis, Botaurus_lentiginosus, Nyctanassa_violacea, Nycticorax_nycticorax,
  Egretta_rufescens, Egretta_tricolor, Egretta_caerulea, Egretta_thula, Ardea_herodias,
  Casmerodius_albus, Bubulcus_ibis, Eudocimus_albus, Plegadis_falcinellus, Plegadis_chihi,
  Platalea_ajaja, Pelecanus_erythrorhynchos, Pelecanus_occidentalis, Coragyps_atratus,
  Cathartes_aura, Mycteria_americana, Gavia_stellata, Gavia_immer, Gavia_adamsii,
  Contopus_cooperi, Contopus_sordidulus, Contopus_virens, Empidonax_flaviventris,
  Empidonax_virescens, Empidonax_alnorum, Empidonax_traillii, Empidonax_minimus, Empidonax_hammondii,
  Empidonax_wrightii, Empidonax_oberholseri, Empidonax_difficilis, Empidonax_occidentalis,
  Sayornis_phoebe, Sayornis_saya, Sayornis_nigricans, Pyrocephalus_rubinus, Myiarchus_crinitus,
  Myiarchus_tyrannulus, Tyrannus_melancholicus, Tyrannus_couchii, Tyrannus_forficatus,
  Tyrannus_tyrannus, Tyrannus_dominicensis, Pitangus_sulphuratus, Lanius_ludovicianus,
  Vireo_bellii, Vireo_atricapilla, Vireo_huttoni, Vireo_griseus, Vireo_cassinii, Vireo_solitarius,
  Vireo_flavifrons, Vireo_philadelphicus, Vireo_olivaceus, Vireo_gilvus, Gymnorhinus_cyanocephalus,
  Cyanocitta_cristata, Cyanocitta_stelleri, Aphelocoma_californica, Perisoreus_canadensis,
  Nucifraga_columbiana, Corvus_brachyrhynchos, Corvus_ossifragus, Corvus_corax, Phainopepla_nitens,
  Bombycilla_garrulus, Bombycilla_cedrorum, Cinclus_mexicanus, Zoothera_naevia, Sialia_sialis,
  Sialia_mexicana, Sialia_currucoides, Myadestes_townsendi, Catharus_fuscescens, Catharus_minimus,
  Catharus_bicknelli, Catharus_guttatus, Hylocichla_mustelina, Turdus_migratorius,
  Sturnus_vulgaris, Dumetella_carolinensis, Mimus_polyglottos, Oreoscoptes_montanus,
  Toxostoma_rufum, Toxostoma_curvirostre, Toxostoma_redivivum, Sitta_pygmaea, Sitta_pusilla,
  Sitta_canadensis, Sitta_carolinensis, Certhia_americana, Campylorhynchus_brunneicapillus,
  Salpinctes_obsoletus, Catherpes_mexicanus, Cistothorus_platensis, Cistothorus_palustris,
  Thryomanes_bewickii, Thryothorus_ludovicianus, Troglodytes_aedon, Auriparus_flaviceps,
  Polioptila_caerulea, Parus_carolinensis, Parus_atricapillus, Parus_gambeli, Parus_rufescens,
  Baeolophus_inornatus, Baeolophus_bicolor, Baeolophus_atricristatus, Psaltriparus_minimus,
  Tachycineta_bicolor, Tachycineta_thalassina, Progne_subis, Stelgidopteryx_serripennis,
  Riparia_riparia, Hirundo_rustica, Petrochelidon_pyrrhonota, Petrochelidon_fulva,
  Regulus_calendula, Regulus_satrapa, Chamaea_fasciata, Eremophila_alpestris, Passer_domesticus,
  Passer_montanus, Anthus_rubescens, Carduelis_pinus, Carduelis_tristis, Carduelis_psaltria,
  Carduelis_lawrencei, Carduelis_hornemanni, Carduelis_flammea, Leucosticte_tephrocotis,
  Leucosticte_atrata, Carpodacus_purpureus, Carpodacus_cassinii, Carpodacus_mexicanus,
  Pinicola_enucleator, Loxia_leucoptera, Coccothraustes_vespertinus, Calcarius_lapponicus,
  Calcarius_pictus, Plectrophenax_nivalis, Calamospiza_melanocorys, Passerella_iliaca,
  Melospiza_melodia, Melospiza_lincolnii, Melospiza_georgiana, Zonotrichia_querula,
  Zonotrichia_albicollis, Zonotrichia_leucophrys, Zonotrichia_atricapilla, Junco_hyemalis,
  Passerculus_sandwichensis, Ammodramus_maritimus, Ammodramus_nelsoni, Ammodramus_henslowii,
  Ammodramus_savannarum, Spizella_arborea, Spizella_passerina, Spizella_pallida, Spizella_breweri,
  Spizella_pusilla, Spizella_atrogularis, Pooecetes_gramineus, Chondestes_grammacus,
  Amphispiza_bilineata, Amphispiza_belli, Aimophila_aestivalis, Aimophila_cassinii,
  Aimophila_ruficeps, Pipilo_chlorurus, Pipilo_maculatus, Pipilo_erythrophthalmus,
  Pipilo_crissalis, Pipilo_aberti, Vermivora_pinus, Vermivora_chrysoptera, Vermivora_peregrina,
  Vermivora_celata, Vermivora_virginiae, Vermivora_luciae, Parula_americana, Dendroica_petechia,
  Dendroica_magnolia, Dendroica_tigrina, Dendroica_coronata, Dendroica_nigrescens,
  Dendroica_townsendi, Dendroica_occidentalis, Dendroica_virens, Dendroica_fusca,
  Dendroica_dominica, Dendroica_pinus, Dendroica_discolor, Dendroica_palmarum, Dendroica_castanea,
  Dendroica_striata, Dendroica_cerulea, Mniotilta_varia, Setophaga_ruticilla, Protonotaria_citrea,
  Helmitheros_vermivorum, Limnothlypis_swainsonii, Seiurus_aurocapilla, Seiurus_noveboracensis,
  Seiurus_motacilla, Oporornis_formosus, Oporornis_agilis, Oporornis_philadelphia,
  Oporornis_tolmiei, Geothlypis_trichas, Wilsonia_citrina, Wilsonia_pusilla, Wilsonia_canadensis,
  Myioborus_pictus, Icteria_virens, Piranga_flava, Piranga_rubra, Piranga_olivacea,
  Piranga_ludoviciana, Spiza_americana, Pheucticus_ludovicianus, Pheucticus_melanocephalus,
  Cardinalis_cardinalis, Cardinalis_sinuatus, Passerina_caerulea, Passerina_amoena,
  Passerina_cyanea, Passerina_versicolor, Passerina_ciris, Icterus_galbula, Icterus_bullockii,
  Icterus_cucullatus, Icterus_spurius, Icterus_parisorum, Xanthocephalus_xanthocephalus,
  Agelaius_phoeniceus, Agelaius_tricolor, Sturnella_magna, Sturnella_neglecta, Quiscalus_mexicanus,
  Quiscalus_major, Quiscalus_quiscula, Euphagus_carolinus, Euphagus_cyanocephalus,
  Molothrus_aeneus, Molothrus_ater, Dolichonyx_oryzivorus, Pica_hudsonia, Dendragapus_fuliginosus,
  Branta_hutchinsii, Anas_fulvigula, Himantopus_mexicanus, Caracara_cheriway, Butorides_virescens,
  Gavia_pacifica]
sample_trees: [EricsonStage2Full_9762.tre, EricsonStage2Full_2001.tre, EricsonStage2Full_6480.tre,
  EricsonStage2Full_3069.tre, EricsonStage2Full_9546.tre, EricsonStage2Full_4033.tre,
  EricsonStage2Full_1711.tre, EricsonStage2Full_2719.tre, EricsonStage2Full_5634.tre,
  EricsonStage2Full_7507.tre, EricsonStage2Full_7421.tre, EricsonStage2Full_4824.tre,
  EricsonStage2Full_4866.tre, EricsonStage2Full_3907.tre, EricsonStage2Full_7050.tre,
  EricsonStage2Full_3189.tre, EricsonStage2Full_9680.tre, EricsonStage2Full_7953.tre,
  EricsonStage2Full_6966.tre, EricsonStage2Full_0884.tre, EricsonStage2Full_0498.tre,
  EricsonStage2Full_6087.tre, EricsonStage2Full_2797.tre, EricsonStage2Full_1876.tre,
  EricsonStage2Full_5237.tre, EricsonStage2Full_0115.tre, EricsonStage2Full_6305.tre,
  EricsonStage2Full_4433.tre, EricsonStage2Full_2354.tre, EricsonStage2Full_7898.tre,
  EricsonStage2Full_9435.tre, EricsonStage2Full_6520.tre, EricsonStage2Full_5697.tre,
  EricsonStage2Full_9103.tre, EricsonStage2Full_8761.tre, EricsonStage2Full_4160.tre,
  EricsonStage2Full_7136.tre, EricsonStage2Full_4310.tre, EricsonStage2Full_8601.tre,
  EricsonStage2Full_9696.tre, EricsonStage2Full_3992.tre, EricsonStage2Full_7708.tre,
  EricsonStage2Full_6697.tre, EricsonStage2Full_5376.tre, EricsonStage2Full_9596.tre,
  EricsonStage2Full_8244.tre, EricsonStage2Full_1537.tre, EricsonStage2Full_8243.tre,
  EricsonStage2Full_4523.tre, EricsonStage2Full_1924.tre, EricsonStage2Full_9118.tre,
  EricsonStage2Full_9892.tre, EricsonStage2Full_6824.tre, EricsonStage2Full_0105.tre,
  EricsonStage2Full_8896.tre, EricsonStage2Full_2335.tre, EricsonStage2Full_1284.tre,
  EricsonStage2Full_0021.tre, EricsonStage2Full_2661.tre, EricsonStage2Full_7513.tre,
  EricsonStage2Full_4507.tre, EricsonStage2Full_3519.tre, EricsonStage2Full_5676.tre,
  EricsonStage2Full_0627.tre, EricsonStage2Full_9921.tre, EricsonStage2Full_8685.tre,
  EricsonStage2Full_5249.tre, EricsonStage2Full_7353.tre, EricsonStage2Full_9607.tre,
  EricsonStage2Full_7862.tre, EricsonStage2Full_9194.tre, EricsonStage2Full_9818.tre,
  EricsonStage2Full_8642.tre, EricsonStage2Full_8186.tre, EricsonStage2Full_5307.tre,
  EricsonStage2Full_8331.tre, EricsonStage2Full_9412.tre, EricsonStage2Full_8876.tre,
  EricsonStage2Full_2029.tre, EricsonStage2Full_8413.tre, EricsonStage2Full_3551.tre,
  EricsonStage2Full_4934.tre, EricsonStage2Full_8264.tre, EricsonStage2Full_1296.tre,
  EricsonStage2Full_8664.tre, EricsonStage2Full_4492.tre, EricsonStage2Full_4321.tre,
  EricsonStage2Full_6404.tre, EricsonStage2Full_4703.tre, EricsonStage2Full_7857.tre,
  EricsonStage2Full_4451.tre, EricsonStage2Full_4270.tre, EricsonStage2Full_3384.tre,
  EricsonStage2Full_2285.tre, EricsonStage2Full_7004.tre, EricsonStage2Full_5017.tre,
  EricsonStage2Full_8187.tre, EricsonStage2Full_4394.tre, EricsonStage2Full_3338.tre,
  EricsonStage2Full_1933.tre]
status: COMPLETED
created_at: "2021-10-03T16:49:03Z"
completed_at: "2021-10-03T16:49:37Z"
bad_names: {EricsonStage2Full_0021.tre: [], EricsonStage2Full_0105.tre: [], EricsonStage2Full_0115.tre: [],
  EricsonStage2Full_0498.tre: [], EricsonStage2Full_0627.tre: [], EricsonStage2Full_0884.tre: [],
  EricsonStage2Full_1284.tre: [], EricsonStage2Full_1296.tre: [], EricsonStage2Full_1537.tre: [],
  EricsonStage2Full_1711.tre: [], EricsonStage2Full_1876.tre: [], EricsonStage2Full_1924.tre: [],
  EricsonStage2Full_1933.tre: [], EricsonStage2Full_2001.tre: [], EricsonStage2Full_2029.tre: [],
  EricsonStage2Full_2285.tre: [], EricsonStage2Full_2335.tre: [], EricsonStage2Full_2354.tre: [],
  EricsonStage2Full_2661.tre: [], EricsonStage2Full_2719.tre: [], EricsonStage2Full_2797.tre: [],
  EricsonStage2Full_3069.tre: [], EricsonStage2Full_3189.tre: [], EricsonStage2Full_3338.tre: [],
  EricsonStage2Full_3384.tre: [], EricsonStage2Full_3519.tre: [], EricsonStage2Full_3551.tre: [],
  EricsonStage2Full_3907.tre: [], EricsonStage2Full_3992.tre: [], EricsonStage2Full_4033.tre: [],
  EricsonStage2Full_4160.tre: [], EricsonStage2Full_4270.tre: [], EricsonStage2Full_4310.tre: [],
  EricsonStage2Full_4321.tre: [], EricsonStage2Full_4394.tre: [], EricsonStage2Full_4433.tre: [],
  EricsonStage2Full_4451.tre: [], EricsonStage2Full_4492.tre: [], EricsonStage2Full_4507.tre: [],
  EricsonStage2Full_4523.tre: [], EricsonStage2Full_4703.tre: [], EricsonStage2Full_4824.tre: [],
  EricsonStage2Full_4866.tre: [], EricsonStage2Full_4934.tre: [], EricsonStage2Full_5017.tre: [],
  EricsonStage2Full_5237.tre: [], EricsonStage2Full_5249.tre: [], EricsonStage2Full_5307.tre: [],
  EricsonStage2Full_5376.tre: [], EricsonStage2Full_5634.tre: [], EricsonStage2Full_5676.tre: [],
  EricsonStage2Full_5697.tre: [], EricsonStage2Full_6087.tre: [], EricsonStage2Full_6305.tre: [],
  EricsonStage2Full_6404.tre: [], EricsonStage2Full_6480.tre: [], EricsonStage2Full_6520.tre: [],
  EricsonStage2Full_6697.tre: [], EricsonStage2Full_6824.tre: [], EricsonStage2Full_6966.tre: [],
  EricsonStage2Full_7004.tre: [], EricsonStage2Full_7050.tre: [], EricsonStage2Full_7136.tre: [],
  EricsonStage2Full_7353.tre: [], EricsonStage2Full_7421.tre: [], EricsonStage2Full_7507.tre: [],
  EricsonStage2Full_7513.tre: [], EricsonStage2Full_7708.tre: [], EricsonStage2Full_7857.tre: [],
  EricsonStage2Full_7862.tre: [], EricsonStage2Full_7898.tre: [], EricsonStage2Full_7953.tre: [],
  EricsonStage2Full_8186.tre: [], EricsonStage2Full_8187.tre: [], EricsonStage2Full_8243.tre: [],
  EricsonStage2Full_8244.tre: [], EricsonStage2Full_8264.tre: [], EricsonStage2Full_8331.tre: [],
  EricsonStage2Full_8413.tre: [], EricsonStage2Full_8601.tre: [], EricsonStage2Full_8642.tre: [],
  EricsonStage2Full_8664.tre: [], EricsonStage2Full_8685.tre: [], EricsonStage2Full_8761.tre: [],
  EricsonStage2Full_8876.tre: [], EricsonStage2Full_8896.tre: [], EricsonStage2Full_9103.tre: [],
  EricsonStage2Full_9118.tre: [], EricsonStage2Full_9194.tre: [], EricsonStage2Full_9412.tre: [],
  EricsonStage2Full_9435.tre: [], EricsonStage2Full_9546.tre: [], EricsonStage2Full_9596.tre: [],
  EricsonStage2Full_9607.tre: [], EricsonStage2Full_9680.tre: [], EricsonStage2Full_9696.tre: [],
  EricsonStage2Full_9762.tre: [], EricsonStage2Full_9818.tre: [], EricsonStage2Full_9892.tre: [],
  EricsonStage2Full_9921.tre: []}
